name: flutter_material_color_picker
description: Material color picker with some possible customizations for Flutter apps
version: 1.0.0
author: Jean-Charles Mouss√© <jeancharles.msse@gmail.com>
homepage: https://github.com/pyozer/color_picker

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'