name: color_picker
description: Color picker for Flutter
version: 0.0.1
author: Jean-Charles Mouss√© <jeancharles.msse@gmail.com>
homepage: https://github.com/pyozer/color_picker

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter