name: flutter_material_color_picker
description: Material color picker with some possible customizations for Flutter apps
version: 1.1.0
homepage: https://github.com/pyozer/color_picker

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'